INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (1, 'Aracruz');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (2, 'Vila Velha');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (3, 'Domingos Martins');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (4, 'Baixo Guandu');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (5, 'Cachoeiro de Itapemirim');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (6, 'Castelo');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (7, 'Colatina');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (8, 'Fundão');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (9, 'Governador Lindenberg');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (10, 'Itapemirim');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (11, 'Marilândia');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (12, 'Vitória');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (13, 'Santa Tereza');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (14, 'São Roque do Canaã');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (15, 'Serra');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (16, 'Linhares');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (17, 'Barra de São Francisco');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (18, 'São Mateus');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (19, 'Mimoso do Sul');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (20, 'Muqui');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (21, 'Vargem Alta');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (22, 'Afonso Cláudio');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (23, 'Água Doce do Norte');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (24, 'Águia Branca');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (25, 'Alegre');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (26, 'Alfredo Chaves');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (27, 'Anchieta');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (28, 'Apiacá');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (29, 'Atílio Vivacqua');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (30, 'Boa Esperança');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (31, 'Bom Jesus do Norte');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (32, 'Cariacica');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (33, 'Conceição da Barra');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (34, 'Conceição do Castelo');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (35, 'Divino de São Lourenço');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (36, 'Dores do Rio Preto');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (37, 'Ecoporanga');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (38, 'Rio Novo do Sul');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (39, 'Guarapari');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (40, 'João Neiva');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (41, 'Nova Venécia');
INSERT INTO cidade(idt_cidade, nome_cidade) VALUES (42, 'Viana');