INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (1, 'FF0000', 'Vermelho');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (2, '00FF00', 'Verde');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (3, 'FF9900', 'Laranja');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (4, 'FF00FF', 'Rosa');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (5, '0000FF', 'Azul');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (6, 'AA00FF', 'Roxo');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (7, 'AA0000', 'Vermelho escuro');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (8, '441111', 'Marrom');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (9, '6D6D6D', 'Cinza');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (10, '00EBFA', 'Verde água');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (11, '004343', 'Verde escuro');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (12, '0077FF', 'Azulzinho');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (13, 'A1CDFF', 'Azulzinha cinza');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (14, 'FFFF00', 'Amarelo');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (15, 'DDDDDD', 'Cinza claro');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (16, '380262', 'Roxo Escuro');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (17, '000000', 'Preto');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (18, '99AE0D', 'Verde amarelado');
INSERT INTO cor (idt_cod, hex, nome_cor) VALUES (19, '7F310E', 'Laranja escuro');